#!/usr/bin/env bash

echo -e "sed -iE 's/listen 8000/listen 80/g' /etc/nginx/sites-enabled/default\
sed -i 's/listen \[::\]:8000/listen \[::\]:80/g' /etc/nginx/sites-enabled/default\n
pgrep nginx -o > /run/nginx.pid\nnginx -s reload\necho'' > /run/nginx.pid" | bash
